---
# handlers file for elasticsearch

- name: Start ssm agent
  ansible.builtin.service:
    name: amazon-ssm-agent.service
    state: started
    enabled: yes

- name: Start Firewall
  ansible.builtin.service:
    name: firewall
    state: started
    enabled: yes

- name: Reload FirewallD
  ansible.builtin.service:
    name: firewalld
    state: reloaded
    enabled: yes